### ISSUE TITLE
pydocumentdb 2.3.5 install failed with homebrew

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cosmos-python#183]
I'm using homebrew to install azure-cli, which depends on pydocumentdb.

With the latest 2.3.5, the install failed with the following message:
```
Processing /private/tmp/azure-cli--pydocumentdb-20191010-73888-8ri94n/pydocumentdb-2.3.5

  Created temporary directory: /private/tmp/pip-req-build-m8z2g0pt

  Added file:///private/tmp/azure-cli--pydocumentdb-20191010-73888-8ri94n/pydocumentdb-2.3.5 to build tracker '/private/tmp/pip-req-tracker-cwd2jeyt'

    Running setup.py (path:/private/tmp/pip-req-build-m8z2g0pt/setup.py) egg_info for package from file:///private/tmp/azure-cli--pydocumentdb-20191010-73888-8ri94n/pydocumentdb-2.3

.5

    Running command python setup.py egg_info

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/tmp/pip-req-build-m8z2g0pt/setup.py", line 10, in <module>

        with open("changelog.md", encoding="utf-8") as f:

    FileNotFoundError: [Errno 2] No such file or directory: 'changelog.md'
```

It seems changelog.md is missing and setup.py throws the error. Please investigate.

**Comment by jonringer** [comment]
this is an issue with the sdist package

**Comment by jonringer** [comment]
should have been fixed in #182

there needs to be a 2.3.6 bump to apply these fixes though

**Comment by glaubitz** [comment]
Could 2.3.6 be released? I just ran into this issue when trying to update ```pydocumentdb``` to 2.3.5 in openSUSE:

```
[    3s] + /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
[    3s] Traceback (most recent call last):
[    3s]   File "setup.py", line 10, in <module>
[    3s]     with open("changelog.md", encoding="utf-8") as f:
[    3s] IOError: [Errno 2] No such file or directory: 'changelog.md'
```
