### ISSUE TITLE
Tests are failing due to connectivity to test server

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cosmos-python#6]
The following instructions are not clear to run the tests:

```

2) To run tests:

    $ python test/crud_tests.py

    If you use Microsoft Visual Studio, open the project file python.pyproj,
    and press F5.
```

I cannot connect to the test server (localhost:443, I believe) and get the following error in all test methods. Is there a way to start the test server with the command above?

``` python
Traceback (most recent call last):
  File "test/crud_tests.py", line 40, in setUp
    databases = client.ReadDatabases().ToArray()
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/query_iterator.py", line 72, in ToArray
    for element in self:
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/query_iterator.py", line 48, in next
    item = self.__FetchOneItem()
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/query_iterator.py", line 105, in __FetchOneItem
    if not self.__FetchMore():
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/query_iterator.py", line 133, in __FetchMore
    self.__options)
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/document_client.py", line 141, in fetch_fn
    options), self.last_response_headers
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/document_client.py", line 1680, in __QueryFeed
    headers)
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/document_client.py", line 1568, in __Get
    headers)
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/synchronized_request.py", line 163, in SynchronizedRequest
    return __InternalRequest(connection_policy, request_options, request_body)
  File "/Users/alp/.virtualenvs/docdb/lib/python2.7/site-packages/pydocumentdb/synchronized_request.py", line 88, in __InternalRequest
    request_options['headers'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
```

Note: running on OS X.

**Comment by rnagpal** [comment]
@ahmetalpbalkan The Readme now contains the instructions to replace this with your account details.
